# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VocaDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VocaDB

  target 'VocaDB-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VocaDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'VocaDB-tvOS' dotv
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for VocaDB-tvOS
#
#  target 'VocaDB-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end

pod 'Firebase/Core'
pod 'Firebase/Database', '~> 5.3.0'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'
pod 'Firebase/RemoteConfig', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'
