# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and submit app to testflight"
  lane :beta do
    xcversion(version: "10.2.1")
    build_ios_app(export_method: "app-store")
    upload_to_testflight
    # add actions here: https://docs.fastlane.tools/actions
  end
end
