export const recentSongs = [
    {
        "artistString": "Move->Forward feat. 初音ミク V4 (English), 初音ミク V3 (English)",
        "createDate": "2018-01-27T22:16:39",
        "defaultName": "The Future, mi futuro",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 0,
        "id": 182652,
        "lengthSeconds": 211,
        "name": "The Future, mi futuro",
        "publishDate": "2018-01-27T00:00:00Z",
        "pvServices": "SoundCloud",
        "ratingScore": 2,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i1.sndcdn.com/artworks-000291782544-viazip-large.jpg",
        "version": 6
    },
    {
        "artistString": "ロレンルイ feat. V3 GUMI (Whisper)",
        "createDate": "2018-01-20T06:09:16",
        "defaultName": "Agua Secreta, Tierra Lejana",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 0,
        "id": 181878,
        "lengthSeconds": 261,
        "name": "Agua Secreta, Tierra Lejana",
        "publishDate": "2017-06-03T00:00:00Z",
        "pvServices": "Youtube",
        "ratingScore": 4,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i.ytimg.com/vi/p8fAR09EwxY/default.jpg",
        "version": 5
    },
    {
        "artistString": "Jyun feat. 初音ミク",
        "createDate": "2017-08-16T15:56:39",
        "defaultName": "Meditations",
        "defaultNameLanguage": "English",
        "favoritedTimes": 0,
        "id": 165389,
        "lengthSeconds": 251,
        "name": "Meditations",
        "publishDate": "2016-12-16T00:00:00Z",
        "pvServices": "NicoNicoDouga",
        "ratingScore": 4,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr1.smilevideo.jp/smile?i=30235332",
        "version": 2
    },
    {
        "artistString": "Jyun feat. 初音ミク",
        "createDate": "2017-08-16T15:54:47",
        "defaultName": "Distance",
        "defaultNameLanguage": "English",
        "favoritedTimes": 0,
        "id": 165388,
        "lengthSeconds": 277,
        "name": "Distance",
        "publishDate": "2016-09-02T00:00:00Z",
        "pvServices": "NicoNicoDouga",
        "ratingScore": 2,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr1.smilevideo.jp/smile?i=29571668",
        "version": 2
    },
    {
        "artistString": "みっち feat. 鏡音リン Append (Unknown)",
        "createDate": "2017-08-14T21:19:12",
        "defaultName": "アイボリー",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 0,
        "id": 165197,
        "lengthSeconds": 231,
        "name": "アイボリー",
        "publishDate": "2011-03-19T00:00:00Z",
        "pvServices": "NicoNicoDouga, Piapro",
        "ratingScore": 0,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr2.smilevideo.jp/smile?i=13900325",
        "version": 3
    },
    {
        "artistString": "Ni-ny feat. ONE",
        "createDate": "2017-08-11T05:58:10",
        "defaultName": "ID",
        "defaultNameLanguage": "English",
        "favoritedTimes": 0,
        "id": 164908,
        "lengthSeconds": 191,
        "name": "ID",
        "publishDate": "2017-08-11T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube, Piapro",
        "ratingScore": 2,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr1.smilevideo.jp/smile?i=31765600",
        "version": 3
    },
    {
        "artistString": "Ni-ny feat. ONE",
        "createDate": "2017-08-11T05:44:08",
        "defaultName": "far away",
        "defaultNameLanguage": "English",
        "favoritedTimes": 0,
        "id": 164907,
        "lengthSeconds": 202,
        "name": "far away",
        "publishDate": "2017-08-06T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube, Piapro",
        "ratingScore": 2,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr3.smilevideo.jp/smile?i=31725038",
        "version": 3
    },
    {
        "artistString": "Nihil feat. 初音ミク",
        "createDate": "2017-08-11T05:16:11",
        "defaultName": "dark survival",
        "defaultNameLanguage": "English",
        "favoritedTimes": 0,
        "id": 164897,
        "lengthSeconds": 253,
        "name": "dark survival",
        "publishDate": "2017-01-11T00:00:00Z",
        "pvServices": "NicoNicoDouga, Piapro",
        "ratingScore": 0,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr3.smilevideo.jp/smile?i=30670654",
        "version": 2
    },
    {
        "artistString": "Nihil feat. 初音ミク",
        "createDate": "2017-08-11T05:09:50",
        "defaultName": "ふたり",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 0,
        "id": 164896,
        "lengthSeconds": 291,
        "name": "ふたり",
        "publishDate": "2017-01-20T00:00:00Z",
        "pvServices": "NicoNicoDouga, Piapro",
        "ratingScore": 4,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr4.smilevideo.jp/smile?i=30480731",
        "version": 3
    },
    {
        "artistString": "Nihil feat. 初音ミク",
        "createDate": "2017-08-11T05:00:20",
        "defaultName": "初音ミクの寂寞",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 0,
        "id": 164895,
        "lengthSeconds": 284,
        "name": "初音ミクの寂寞",
        "publishDate": "2016-09-19T00:00:00Z",
        "pvServices": "NicoNicoDouga, Piapro",
        "ratingScore": 0,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr2.smilevideo.jp/smile?i=30198789",
        "version": 3
    }
];

export const popularSongs = [
    {
        "artistString": "黒うさP feat. 初音ミク",
        "createDate": "2012-01-14T17:17:31",
        "defaultName": "千本桜",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 110,
        "id": 8394,
        "lengthSeconds": 245,
        "name": "千本桜",
        "publishDate": "2011-09-17T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 292,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr3.smilevideo.jp/smile?i=15630734",
        "version": 25
    },
    {
        "artistString": "ハチ feat. 初音ミク, GUMI",
        "createDate": "2011-10-11T17:06:11",
        "defaultName": "マトリョシカ",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 99,
        "id": 368,
        "lengthSeconds": 201,
        "name": "マトリョシカ",
        "publishDate": "2010-08-19T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 274,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i.ytimg.com/vi/HOz-9FzIDf0/default.jpg",
        "version": 24
    },
    {
        "artistString": "wowaka feat. 初音ミク",
        "createDate": "2011-11-01T22:10:01",
        "defaultName": "ローリンガール",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 79,
        "id": 1501,
        "lengthSeconds": 196,
        "name": "ローリンガール",
        "publishDate": "2010-02-14T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube, SoundCloud",
        "ratingScore": 353,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr4.smilevideo.jp/smile?i=9714351",
        "version": 17
    },
    {
        "artistString": "ryo feat. 初音ミク",
        "createDate": "2012-08-12T00:55:23",
        "defaultName": "ODDS&ENDS",
        "defaultNameLanguage": "English",
        "favoritedTimes": 72,
        "id": 15662,
        "lengthSeconds": 354,
        "name": "ODDS&ENDS",
        "publishDate": "2012-08-14T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube, SoundCloud",
        "ratingScore": 304,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i.ytimg.com/vi/iOFZKwv_LfA/default.jpg",
        "version": 21
    },
    {
        "artistString": "kz feat. 初音ミク",
        "createDate": "2012-01-14T17:36:16",
        "defaultName": "Tell Your World",
        "defaultNameLanguage": "English",
        "favoritedTimes": 67,
        "id": 8395,
        "lengthSeconds": 257,
        "name": "Tell Your World",
        "publishDate": "2012-01-18T00:00:00Z",
        "pvServices": "Youtube, SoundCloud",
        "ratingScore": 325,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://i.ytimg.com/vi/PqJNc9KVIZE/default.jpg",
        "version": 20
    },
    {
        "artistString": "Neru feat. 鏡音リン Append (Power)",
        "createDate": "2012-12-21T17:47:14",
        "defaultName": "ロストワンの号哭",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 64,
        "id": 19094,
        "lengthSeconds": 217,
        "name": "ロストワンの号哭",
        "publishDate": "2013-03-04T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 276,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr3.smilevideo.jp/smile?i=20244918",
        "version": 18
    },
    {
        "artistString": "iroha(sasaki) feat. 鏡音リン",
        "createDate": "2011-11-07T12:07:40",
        "defaultName": "炉心融解",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 60,
        "id": 3022,
        "lengthSeconds": 333,
        "name": "炉心融解",
        "publishDate": "2008-12-19T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube, SoundCloud",
        "ratingScore": 280,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr2.smilevideo.jp/smile?i=8089993",
        "version": 26
    },
    {
        "artistString": "Last Note. feat. GUMI",
        "createDate": "2012-05-03T14:50:03",
        "defaultName": "セツナトリップ",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 56,
        "id": 11807,
        "lengthSeconds": 249,
        "name": "セツナトリップ",
        "publishDate": "2012-05-03T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 140,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "http://tn-skr4.smilevideo.jp/smile?i=17720979",
        "version": 18
    },
    {
        "artistString": "kz feat. 初音ミク",
        "createDate": "2011-11-04T05:19:51",
        "defaultName": "Last Night, Good Night",
        "defaultNameLanguage": "English",
        "favoritedTimes": 52,
        "id": 2443,
        "lengthSeconds": 396,
        "name": "Last Night, Good Night",
        "publishDate": "2007-12-30T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 226,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i.ytimg.com/vi/T6mMMYSqlM4/default.jpg",
        "version": 24
    },
    {
        "artistString": "ギガP feat. 初音ミク V3 (Solid)",
        "createDate": "2014-08-08T10:59:38",
        "defaultName": "ヒビカセ",
        "defaultNameLanguage": "Japanese",
        "favoritedTimes": 52,
        "id": 63276,
        "lengthSeconds": 250,
        "name": "ヒビカセ",
        "publishDate": "2014-08-17T00:00:00Z",
        "pvServices": "NicoNicoDouga, Youtube",
        "ratingScore": 262,
        "songType": "Original",
        "status": "Approved",
        "thumbUrl": "https://i.ytimg.com/vi/TkroHwQYpFE/default.jpg",
        "version": 20
    }
];

export const popularAlbums = [
    {
        "artistString": "ラマーズP feat. various",
        "createDate": "2017-09-15T17:42:20",
        "defaultName": "まえむきになれるきょく",
        "defaultNameLanguage": "Japanese",
        "discType": "Album",
        "id": 23294,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23294.jpg?v=3",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23294.jpg?v=3",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23294.jpg?v=3"
        },
        "name": "まえむきになれるきょく",
        "ratingAverage": 5,
        "ratingCount": 3,
        "releaseDate": {
            "day": 15,
            "formatted": "9/15/2017",
            "isEmpty": false,
            "month": 9,
            "year": 2017
        },
        "status": "Approved",
        "version": 3
    },
    {
        "artistString": "regulus feat. various",
        "catalogNumber": "KRHS-94365",
        "createDate": "2017-09-05T07:23:59",
        "defaultName": "Plastic Hearts",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 23267,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23267.jpg?v=7",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23267.jpg?v=7",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23267.jpg?v=7"
        },
        "name": "Plastic Hearts",
        "ratingAverage": 4.16,
        "ratingCount": 6,
        "releaseDate": {
            "day": 2,
            "formatted": "9/2/2017",
            "isEmpty": false,
            "month": 9,
            "year": 2017
        },
        "status": "Approved",
        "version": 7
    },
    {
        "artistString": "korby, 畑中洋光 feat. 初音ミク",
        "createDate": "2017-08-28T11:32:43",
        "defaultName": "SCENES",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 23220,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23220.jpg?v=5",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23220.jpg?v=5",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23220.jpg?v=5"
        },
        "name": "SCENES",
        "ratingAverage": 5,
        "ratingCount": 1,
        "releaseDate": {
            "day": 28,
            "formatted": "8/28/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 5
    },
    {
        "artistString": "Various artists",
        "catalogNumber": "ADSR-0009",
        "createDate": "2017-08-27T12:20:44",
        "defaultName": "VOCALO EDM SESSIONS",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 23209,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23209.png?v=10",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23209.png?v=10",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23209.png?v=10"
        },
        "name": "VOCALO EDM SESSIONS",
        "ratingAverage": 4.5,
        "ratingCount": 4,
        "releaseDate": {
            "day": 11,
            "formatted": "8/11/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 10
    },
    {
        "artistString": "ばぶちゃん, ゲボ吐き糞野郎, CHOCOSONG feat. 初音ミク",
        "createDate": "2017-07-28T23:36:10",
        "defaultName": "ばぶらんど",
        "defaultNameLanguage": "Japanese",
        "discType": "Album",
        "id": 23031,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23031.png?v=9",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23031.png?v=9",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23031.png?v=9"
        },
        "name": "ばぶらんど",
        "ratingAverage": 3.5,
        "ratingCount": 2,
        "releaseDate": {
            "day": 11,
            "formatted": "8/11/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 9
    },
    {
        "artistString": "ひとしずくP, やま△, teamOS feat. various",
        "catalogNumber": "KRHS-94354",
        "createDate": "2017-08-02T14:36:40",
        "defaultName": "VILLAINS & HEROES ~Side:H~",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 23069,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23069.jpg?v=11",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23069.jpg?v=11",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23069.jpg?v=11"
        },
        "name": "VILLAINS & HEROES ~Side:H~",
        "ratingAverage": 4,
        "ratingCount": 1,
        "releaseDate": {
            "day": 11,
            "formatted": "8/11/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 11
    },
    {
        "artistString": "卑屈P feat. various",
        "catalogNumber": "HKTP-0009",
        "createDate": "2017-07-31T16:04:36",
        "defaultName": "ミライサイト",
        "defaultNameLanguage": "Japanese",
        "discType": "Album",
        "id": 23047,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23047.jpg?v=6",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23047.jpg?v=6",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23047.jpg?v=6"
        },
        "name": "ミライサイト",
        "ratingAverage": 0,
        "ratingCount": 0,
        "releaseDate": {
            "day": 11,
            "formatted": "8/11/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 6
    },
    {
        "artistString": "オカメP feat. 初音ミク Append (Dark), 巡音ルカ",
        "catalogNumber": "KRHS-94299",
        "createDate": "2017-08-09T11:28:49",
        "defaultName": "Die For You",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 23103,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/23103.jpg?v=8",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/23103.jpg?v=8",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/23103.jpg?v=8"
        },
        "name": "Die For You",
        "ratingAverage": 5,
        "ratingCount": 6,
        "releaseDate": {
            "day": 9,
            "formatted": "8/9/2017",
            "isEmpty": false,
            "month": 8,
            "year": 2017
        },
        "status": "Approved",
        "version": 8
    },
    {
        "artistString": "TakeponG feat. 結月ゆかり V4 (Unknown)",
        "catalogNumber": "KRHS-94264",
        "createDate": "2017-06-28T12:19:37",
        "defaultName": "Ripple & Revive",
        "defaultNameLanguage": "English",
        "discType": "Album",
        "id": 22956,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/22956.jpg?v=3",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/22956.jpg?v=3",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/22956.jpg?v=3"
        },
        "name": "Ripple & Revive",
        "ratingAverage": 3,
        "ratingCount": 1,
        "releaseDate": {
            "day": 28,
            "formatted": "6/28/2017",
            "isEmpty": false,
            "month": 6,
            "year": 2017
        },
        "status": "Approved",
        "version": 3
    },
    {
        "artistString": "マイナスP, じーざすP, ワンダフル☆オポチュニティ！ feat. 鏡音リン, 鏡音レン",
        "catalogNumber": "WOCD-022",
        "createDate": "2017-04-20T11:41:38",
        "defaultName": "ワン☆オポ！VOL.12",
        "defaultNameLanguage": "Japanese",
        "discType": "Album",
        "id": 22728,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/album/mainSmall/22728.png?v=9",
            "urlThumb": "https://static.vocadb.net/img/album/mainThumb/22728.png?v=9",
            "urlTinyThumb": "https://static.vocadb.net/img/album/mainTiny/22728.png?v=9"
        },
        "name": "ワン☆オポ！VOL.12",
        "ratingAverage": 4,
        "ratingCount": 2,
        "releaseDate": {
            "day": 29,
            "formatted": "4/29/2017",
            "isEmpty": false,
            "month": 4,
            "year": 2017
        },
        "status": "Approved",
        "version": 9
    }
];

export const latestEvents =  [
    {
        "category": "Unspecified",
        "date": "2018-02-18T00:00:00Z",
        "id": 1716,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/releaseeventseries/mainSmall/88.png?v=4",
            "urlThumb": "https://static.vocadb.net/img/releaseeventseries/mainThumb/88.png?v=4",
            "urlTinyThumb": "https://static.vocadb.net/img/releaseeventseries/mainTiny/88.png?v=4"
        },
        "name": "VOCALOID-ManiaX 39",
        "seriesId": 88,
        "seriesNumber": 39,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "vocaloid-maniax-39",
        "venueName": "MOGRA, Akihabara, Tokyo, Japan",
        "version": 2
    },
    {
        "category": "Unspecified",
        "date": "2018-02-14T00:00:00Z",
        "id": 1714,
        "name": "Kokone's Birthday 2018",
        "seriesId": 39,
        "seriesNumber": 2018,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "kokones-birthday-2018",
        "version": 2
    },
    {
        "category": "Unspecified",
        "date": "2018-02-04T00:00:00Z",
        "id": 1708,
        "name": "MEIKO新生祭 2018",
        "seriesId": 7,
        "seriesNumber": 2018,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "meikos-re-birthday-2018",
        "version": 5
    },
    {
        "category": "Unspecified",
        "date": "2018-01-30T00:00:00Z",
        "id": 1705,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/releaseevent/mainSmall/1705.jpg?v=7",
            "urlThumb": "https://static.vocadb.net/img/releaseevent/mainThumb/1705.jpg?v=7",
            "urlTinyThumb": "https://static.vocadb.net/img/releaseevent/mainTiny/1705.jpg?v=7"
        },
        "name": "Luka's Birthday 2018",
        "seriesId": 12,
        "seriesNumber": 2018,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "lukas-birthday-2018",
        "version": 7
    },
    {
        "category": "Unspecified",
        "date": "2015-08-26T00:00:00Z",
        "endDate": "2015-10-19T00:00:00Z",
        "id": 1699,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/releaseevent/mainSmall/1699.jpg?v=2",
            "urlThumb": "https://static.vocadb.net/img/releaseevent/mainThumb/1699.jpg?v=2",
            "urlTinyThumb": "https://static.vocadb.net/img/releaseevent/mainTiny/1699.jpg?v=2"
        },
        "name": "Miku Expo 2015 Song Contest",
        "seriesId": 82,
        "seriesNumber": 2015,
        "seriesSuffix": "Song Contest",
        "status": "Finished",
        "urlSlug": "miku-expo-2015-song-contest",
        "version": 2
    },
    {
        "category": "Unspecified",
        "date": "2016-05-22T00:00:00Z",
        "id": 1697,
        "name": "Momo's Birthday 2016",
        "seriesId": 139,
        "seriesNumber": 2016,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "momos-birthday-2016",
        "version": 2
    },
    {
        "category": "Unspecified",
        "date": "2013-10-10T00:00:00Z",
        "id": 1684,
        "name": "Teto Day 2013",
        "seriesId": 136,
        "seriesNumber": 2013,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "teto-day-2013",
        "version": 3
    },
    {
        "category": "Contest",
        "date": "2017-12-04T00:00:00Z",
        "endDate": "2018-02-04T00:00:00Z",
        "id": 1681,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/releaseevent/mainSmall/1681.jpg?v=11",
            "urlThumb": "https://static.vocadb.net/img/releaseevent/mainThumb/1681.jpg?v=11",
            "urlTinyThumb": "https://static.vocadb.net/img/releaseevent/mainTiny/1681.jpg?v=11"
        },
        "name": "Interspace Love Message (Remix Contest)",
        "seriesNumber": 0,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "interspace-love-message-remix-",
        "version": 11
    },
    {
        "category": "Unspecified",
        "date": "2018-01-21T00:00:00Z",
        "id": 1671,
        "mainPicture": {
            "urlSmallThumb": "https://static.vocadb.net/img/releaseevent/mainSmall/1671.jpg?v=3",
            "urlThumb": "https://static.vocadb.net/img/releaseevent/mainThumb/1671.jpg?v=3",
            "urlTinyThumb": "https://static.vocadb.net/img/releaseevent/mainTiny/1671.jpg?v=3"
        },
        "name": "COMIC CITY 福岡 45",
        "seriesId": 17,
        "seriesNumber": 45,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "comic-city--45",
        "version": 3
    },
    {
        "category": "Unspecified",
        "date": "2017-12-27T00:00:00Z",
        "id": 1669,
        "name": "Kagamine Birthday 2017",
        "seriesId": 10,
        "seriesNumber": 2017,
        "seriesSuffix": "",
        "status": "Finished",
        "urlSlug": "kagamine-birthday-2017",
        "version": 3
    }
]