
export const lyricJp = {
        "cultureCode": "ja",
        "id": 543,
        "source": "",
        "translationType": "Original",
        "url": "",
        "value": "私の恋を悲劇のジュリエットにしないで\r\nここから連れ出して...\r\n\r\nそんな気分よ\r\n\r\nパパとママにおやすみなさい\r\nせいぜい いい夢をみなさい\r\n大人はもう寝る時間よ\r\n\r\n咽返（むせかえ）る魅惑のキャラメル\r\n恥じらいの素足をからめる\r\n今夜はどこまでいけるの？\r\n\r\n噛みつかないで 優しくして\r\n苦いものはまだ嫌いなの\r\nママの作るお菓子ばかり食べたせいね\r\n\r\n知らないことがあるのならば\r\n知りたいと思う 普通でしょ？\r\n全部見せてよ\r\nあなたにならば見せてあげる私の...\r\n\r\nずっと恋しくてシンデレラ\r\n制服だけで駆けていくわ\r\n魔法よ時間を止めてよ\r\n悪い人に 邪魔されちゃうわ\r\n\r\n逃げ出したいのジュリエット\r\nでもその名前で呼ばないで\r\nそうよね 結ばれなくちゃね\r\nそうじゃないと楽しくないわ\r\n\r\nねえ 私と生きてくれる？\r\n\r\n背伸びをした長いマスカラ\r\nいい子になるよきっと明日から\r\n今だけ私を許して\r\n\r\n黒いレースの境界線\r\n守る人は今日はいません\r\n越えたらどこまでいけるの？\r\n\r\n噛みつくほどに 痛いほどに\r\n好きになってたのは私でしょ\r\nパパはでもねあなたのこと嫌いみたい\r\n\r\n私のためと差し出す手に\r\n握ってるそれは首輪でしょ\r\n連れ出してよ 私のロミオ\r\n叱られるほど遠くへ\r\n\r\n鐘が鳴り響くシンデレラ\r\nガラスの靴は置いていくわ\r\nだからね 早く見つけてね\r\n悪い夢に 焦らされちゃうわ\r\n\r\nきっとあの子もそうだった\r\n落としたなんて嘘をついた\r\nそうよね 私も同じよ\r\nだってもっと愛されたいわ\r\n\r\nほら 私はここにいるよ\r\n\r\n私の心そっと覗いてみませんか\r\n欲しいものだけあふれかえっていませんか\r\nまだ別腹よもっともっとぎゅっと詰め込んで\r\nいっそあなたの居場所までも埋めてしまおうか\r\n\r\nでもそれじゃ意味ないの\r\n\r\n大きな箱より 小さな箱に幸せはあるらしい\r\nどうしよこのままじゃ私は\r\nあなたに嫌われちゃうわ\r\n\r\nでも私より欲張りなパパとママは今日も変わらず\r\nそうよね 素直でいいのね\r\n落としたのは金の斧でした\r\n\r\n嘘つきすぎたシンデレラ\r\nオオカミに食べられたらしい\r\nどうしようこのままじゃ私も\r\nいつかは食べられちゃうわ\r\n\r\nその前に助けに来てね"
}

export const lyricRomanji = {
    "cultureCode": "",
    "id": 3360,
    "source": "",
    "translationType": "Romanized",
    "url": "",
    "value": "watashi no koi o higeki no jurietto ni shinaide\r\nkoko kara tsuredashite...\r\n\r\nsonna kibun yo\r\n\r\npapa to mama ni oyasuminasai\r\nseizei  ii yume o minasai\r\notona wa mou neru jikan yo\r\n\r\nmusekaeru miwaku no kyarameru\r\nhajirai no suashi o karameru\r\nkonya wa doko made ikeru no?\r\n\r\nkamitsukanaide  yasashiku shite\r\nnigaimono wa mada kirai na no\r\nmama no tsukuru okashi bakari tabeta sei ne\r\n\r\nshiranai koto ga aru no naraba\r\nshiritai to omou  futsuu desho?\r\nzenbu misete yo\r\nanata ni naraba misete ageru watashi no...\r\n\r\nzutto koishikute shinderera\r\nseifuku dake de kakete yuku wa\r\nmahou yo jikan o tomete yo\r\nwarui hito ni jamasarechau wa\r\n\r\nnigedashitai no jurietto\r\ndemo sono namae de yobanaide\r\nsou yo ne  musubarenakucha ne\r\nsou ja nai to tanoshikunai wa\r\n\r\nnee  watashi to ikite kureru?\r\n\r\nsenobi o shita nagai masukara\r\nii ko ni naru yo kitto asu kara\r\nima dake watashi o yurushite\r\n\r\nkuroi reesu no kyoukaisen\r\nmamoru hito wa kyou wa imasen\r\nkoetara doko made ikeru no?\r\n\r\nkamitsuku hodo ni  itai hodo ni\r\nsuki ni natteta no wa watashi desho\r\npapa wa demo ne anata no koto kirai mitai\r\n\r\nwatashi no tame to sashidasu te ni\r\nnigitteru sore wa kubiwa desho\r\ntsuredashite yo  watashi no romio\r\nshikarareru hodo tooku e\r\n\r\nkane ga narihibiku shinderera\r\ngarasu no kutsu wa oite yuku wa\r\ndakara ne  hayaku mitsukete ne\r\nwarui yume ni  jirasarechau wa\r\n\r\nkitto ano ko mo sou datta\r\notoshita nante uso o tsuita\r\nsou yo ne  watashi mo onaji yo\r\ndatte motto aisaretai wa\r\n\r\nhora  watashi wa koko ni iru yo\r\n\r\nwatashi no kokoro sotto nozoite mimasen ka\r\nhoshii mono dake afurekaette imasen ka\r\nmada betsuhara yo motto motto gyutto tsumekonde\r\nisso anata no ibasho made mo umete shimaou ka\r\n\r\ndemo sore ja imi nai no\r\n\r\nookina hako yori  chiisana hako ni shiawase wa aru rashii\r\ndou shiyou kono mama ja watashi wa\r\nanata ni kirawarechau wa\r\n\r\ndemo watashi yori yokubari na papa to mama wa kyou mo kawarazu\r\nsou yo ne  sunao de ii no ne\r\notoshita no wa kin no ono deshita\r\n\r\nusotsukisugita shinderera\r\nookami ni taberareta rashii\r\ndou shiyou kono mama ja watashi mo\r\nitsuka wa taberarechau wa\r\n\r\nsono mae ni tasuke ni kite ne"
}

export const lyricEng = {
    "cultureCode": "en",
    "id": 3361,
    "source": "Project DIVA F 2nd, marvelangga and ElectricRaichu",
    "translationType": "Translation",
    "url": "http://vocaloidlyrics.wikia.com/wiki/Romeo_and_Cinderella",
    "value": "Don't make my love your tragic Juliet\nTake me away...\n\nThat's how I feel\n\nTell Mom and Dad goodnight\nWish them sweet dreams, at least\nIt's bedtime for grownups\n\nChoking on captivating caramel\nEntwining my bare, bashful legs\nHow far can we venture tonight?\n\nBe gentle, don't bite\nI still dislike bitter tastes\nHaving been spoiled on Mom's homemade sweets\n\nWhen there's something you don't know\nIt's only natural to want to find out\nShow me everything\nAnd just for you, I'll show you mine too...\n\nI'm a Cinderella, yearning for you\nI'll come running in my school uniform\nOh magic, please stop the hands of time\nBefore the villain interferes\n\nI'm a Juliet who wants to run away\nBut don't call me by that name\nWe have to live happily ever after\nOtherwise where's the fun?\n\nTell me, will you choose life?\n\nI applied a little too much mascara\nBut I'll be a good girl when tomorrow comes\nSo please let me off the hook for now\n\nThe boundary line is just this black lace\nAnd there's no one to guard it today so,\nIf you cross it, how far are you going to go?\n\nEnough you bite me, enough to make me hurt\nI'm the one you fell in love with, right?\nBut papa doesn't seem to like you that much\n\nYou say you're holding out your hands for my sake\nBut isn't that a collar you're holding?\nJust take me away, oh my Romeo,\nFar enough away that they scold us\n\nThe bells are going to sound and\nCinderella has to leave her glass shoe\nObviously, you have to look for her quick\nOr she'll be haunted with nightmares\n\nDefinitely, even she did it like that--\nShe lied when she said she \"accidentally\" dropped it\nThat's right; same with me\nSince I want to be loved by you more\n\nLook, I am right here\n\nWon't you peek into my heart?\nSee how it brims with desires?\nI've got room for more, pack my heart until it's full\nUntil it fills up the place where you are\n\nBut what would be the point?\n\nThey say happiness comes in small packages\nIf something doesn't change\nYou're going to end up hating me\n\nBut Mom and Dad are the same as ever, they just want more\nYou're right, I should be honest\nThe axe I dropped was one of gold\n\nCinderella told one too many lives\nand got herself swallowed by the wolf\nIf something doesn't change\nHe's going to end up eating me too\n\nCome to my rescue, before it's too late!"
}