# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play as Internal track"
  lane :internal do
    # https://docs.fastlane.tools/actions/upload_to_play_store/
    upload_to_play_store(track: "internal", 
    version_code:102439, 
    aab: "../build/app/outputs/bundle/release/app-release.aab")
  end

  desc "Get current version codes on production"
  lane :current do
    google_play_track_version_codes
    google_play_track_release_names
  end
end
